import { Footer, Navbar, Providers } from "@/components/shared";
import type { Metadata } from "next";
import { Outfit, Raleway } from "next/font/google";
import { FC } from "react";
import "./globals.css";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

export const metadata: Metadata = {
  title: "TypeShort",
  description: "Generated by Sunnah IT, Powered by Baitul Hikmah Team",
};

const RootLayout: FC<Readonly<IChildren>> = ({ children }) => (
  <html lang="en">
    <body className={`${raleway.variable} ${outfit.variable}`}>
      <Providers>
        <Navbar />
        {children}
        <Footer />
      </Providers>
    </body>
  </html>
);

export default RootLayout;
